superlists/lists/urls.py
from django.conf.urls import url

from . import views


urlpatterns = [
    url(r'^new$', views.new_list, name='new_list'),
    url(r'^(\d+)/$', views.view_list, name='view_list'),
]

superlists/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from superlists.lists import views as list_views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', list_views.homepage, name='home'),
    url(r'^lists/', include('superlists.lists.urls', namespace='lists'),),
]

superlists/lists/models.py
from django.db import models
from django.core.urlresolvers import reverse


class List(models.Model):

    def get_absolute_url(self):
        return reverse('lists:view_list', args=[self.id])


class Item(models.Model):
    text = models.TextField(default='')
    list = models.ForeignKey(List, default=None)

    def __repr__(self):
        return self.text

    class Meta:
        ordering = ('id',)
        unique_together = ('list', 'text')

superlists/lists/forms.py
from django import forms
from django.core.exceptions import ValidationError
from .models import Item


EMPTY_LIST_ERROR = "You can't have an empty list item"
DUPLICATE_ITEM_ERROR = "You've already got this in your list"


class ItemForm(forms.ModelForm):

    use_required_attribute = False

    # noinspection PyMethodOverriding
    def save(self, for_list):
        """

        :type for_list: List
        """
        self.instance.list = for_list
        return super().save()

    class Meta:
        model = Item
        fields = ('text',)
        widgets = {
            'text': forms.fields.TextInput(attrs={
                'placeholder': 'Enter a to-do item',
                'class': 'form-control input-group-lg'
            }),
        }
        error_messages = {
            'text': {'required': EMPTY_LIST_ERROR}
        }


class ExistingListItemForm(ItemForm):

    def __init__(self, for_list, *args, **kwargs):

        super().__init__(*args, **kwargs)
        self.instance.list = for_list

    def validate_unique(self):
        try:
            self.instance.validate_unique()
        except ValidationError as e:
            e.error_dict = {'text': [DUPLICATE_ITEM_ERROR]}
            self._update_errors(e)

    def save(self):
        return forms.ModelForm.save(self)

lists/views.py
from django.shortcuts import render
from django.http import HttpResponse


def homepage(request):
    return HttpResponse(b'<html><title>To-Do lists</title></html>')

superlists/lists/views.py
from django.shortcuts import render, redirect

from .forms import ItemForm, ExistingListItemForm
from .models import List


def homepage(request):

    return render(request, 'lists/homepage.html', {'form': ItemForm()})


def new_list(request):

    form = ItemForm(data=request.POST)

    if form.is_valid():
        list_ = List.objects.create()
        form.save(for_list=list_)
        return redirect(list_)
    else:
        return render(request, 'lists/homepage.html', {'form': form})


def view_list(request, list_id):

    list_ = List.objects.get(id=list_id)
    form = ExistingListItemForm(for_list=list_)

    if request.method == 'POST':
        form = ExistingListItemForm(data=request.POST, for_list=list_)
        if form.is_valid():
            form.save()
            return redirect(list_)

    return render(request, 'lists/list.html', {'list': list_, 'form': form})

superlists/templates/lists/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
      <title>To-Do lists</title>
      <meta http-equiv="X-UA-Compatible" content="IE=edge">
      <meta name="viewport" content="width=device-width, initial-scale=1">
      {% load staticfiles %}
      <link href="{% static "bootstrap/dist/css/bootstrap.min.css" %}"
            rel="stylesheet" media="screen">
      <link href="{% static 'lists/base.css' %}"
            rel="stylesheet" media="screen">

  </head>
  <body>
  <div class="container">
      <div class="row">
          <div class="col-md-6 offset-3 jumbotron">
              <div class="text-center">
                  <h1>
                      {% block header_text %}{% endblock %}
                  </h1>
                  <form method="POST" action="{% block form_action %}{% endblock %}">
                      <label for="id_text">Item</label>
                      {{ form.text }}
                      {% if form.errors %}
                          <div class="form-group alert-danger">
                              <span class="form-text">{{ form.text.errors }}</span>
                          </div>
                      {% endif %}
                  </form>
              </div>
          </div>
      </div>
      <div class="row">
          <div class="col-md-6 col-md-offset-3">
              {% block table %}{% endblock %}
          </div>
      </div>
  </div>
  <script src={% static "lists/jquery-3.4.1.min.js" %}></script>
  <script src={% static "lists/lists.js" %}></script>
  </body>
</html>

superlists/templates/lists/homepage.html
{% extends 'lists/base.html' %}

{% block header_text %}Start a new To-Do list{% endblock %}

{% block form_action %}
    {% url 'lists:new_list' %}
{% endblock %}

superlists/templates/lists/list.html
{% extends 'lists/base.html' %}

{% block header_text %}
Your To-Do list
{% endblock %}

{% block form_action %}
    {% url 'lists:view_list' list.id %}
{% endblock %}

{% block table %}
    <table id="id_list_table" class="table">
        {% for item in list.item_set.all %}
        <tr><td>{{ forloop.counter }}: {{ item.text }}</td></tr>
        {% endfor %}
    </table>
{% endblock %}